apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-runner-work
  labels:
    app.kubernetes.io/part-of: arc-runners
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
