apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: actions-runner-controller
  namespace: argocd

spec:
  project: applications
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: {{ .Values.destination.server }}
    namespace: arc-systems

  sources:
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set-controller
      targetRevision: 0.9.2
      helm:
        valuesObject:

    # - repoURL: {{ .Values.repository.url }}
    #   path: apps/extras/actions-runner-controller
    #   targetRevision: HEAD
    #   helm:
    #     valuesObject:
    #       domain: {{ .Values.domain }}
