apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: applications
  namespace: argocd

# Same as the default project
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
