
# The domain this cluster runs for
domain: "sciwhiz12.dev"

destination:
  # The target K8s server. Unlikely to be changed.
  server: "https://kubernetes.default.svc"

repository:
  # The online repository URL. This must match the URL used in initial configuration.
  url: "git@github.com:sciwhiz12/infrastructure.git"

# Set this to 'true' on the first install, and 'false' directly afterwards once sync finishes
# Needed for jobs that must not run on first install (such as Longhorn's pre-upgrade job)
firstInstall: false

# The ingress class name. Change if not using ingress-nginx.
ingressClassName: nginx

# Argo CD
argo:
  # The subdomain for the Argo ingress (<domainName>.<domain>)
  domainName: argo
  # Domain override for the Argo ingress; if set, argo.domainName is unused
  domainOverride: ~