
project: core

destination:
  # The target K8s server. Unlikely to be changed.
  server: "https://kubernetes.default.svc"

repository:
  # The online repository URL
  url: "https://github.com/sciwhiz12/infrastructure"
