apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    apiKey: AgA3zpuESetetCaAb5cXDh/5hW50ibO1yLh2zIPN2bQqWBfoQiBXhwLRE+xR3lP3N69ZuxnAtzvoH1ugwdgkyswShXIYPn6N/3hoes51nZwnFNb5d6XtLYXozzjoseY00IOLwv6uanv2rEXsqnsdBI3Km3KimwV4dUwhh7M+z2WLTNQn6hXJznM7ZbXrMuF5nny3k3qAa4Fsve5dqaiG8ofT83Ey+ZUioT+dg9CtBua3D+xgzXrItiYVBo7GoBZugulQOWypP0/q0JcYM1s3+A6RyR7YaUnDXXBZbRSylapNzI+85kVlXSC6TtoI/7pWnZLSjcMyTUs83YQ723sxj7rGqWDXUeaVk0dFHHmgbwJVa9NJQ99kqonE0S7RwTj5ZfuBaGZ3Q18UCdLggptTQEGqDGJ4aXkdjLu8MER4kQ78+EL8PdQsgsWOOXIeRO1ran46LfkdkH+M7U4VR5X7x41xVzsrZm80jMryXqcNX+LY+KAInGI4CEjcVGSvLBztw9qICYiclnDEMrhh8ZOUmTRIiLWJphyHmjwkTpRzI8fqp8xMY/JL1D2JPojaKqeABU+74fAvHe9FTCx6BIDVSZu3Z46dFdMEtoVpriKjFxw/i7FZfwXUzTUke3vT209x2oAFbOPvJpDnATiV9g89t7VNG2J/OPmbKrTKctHSArz5IFCgg+shJHGYawrbiwyBE5RXIBzId9QlxhhmqE0xJLty8QlVe4xzLiC7pC3Ge/9Dk0++uDZ2o92G
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
      labels:
        app.kubernetes.io/part-of: external-dns
