apiVersion: v2
name: vaultwarden
description: Extra definitions for vaultwarden

type: application
version: 1.0.0

dependencies:
  - name: mariadb
    version: 18.2.0
    repository: registry-1.docker.io/bitnamicharts
    condition: mariadb.enabled
