apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: argocd
  namespace: argocd

spec:
  project: core-services
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: {{ .Values.destination.server }}
    namespace: argocd

  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 6.10.2
      chart: argo-cd
      helm:
        values: |
          global:
            domain: {{ or .Values.argo.domainOverride (print (or .Values.argo.domainName "argo") "." (or .Values.clusterDomain .Values.domain)) }}

          configs:
            params:
              server.insecure: true # Disable TLS, since we rely on our ingress for SSL
            secret:
              githubSecret: $github-webhook-secret:webhook-secret # Secret token for GitHub webhooks

          server:
            ingress:
              enabled: true
              ingressClassName: {{ .Values.ingressClassName }} # Uses ingress-nginx
              annotations:
                nginx.ingress.kubernetes.io/force-ssl-redirect: "true" # Always use HTTPS
                nginx.ingress.kubernetes.io/backend-protocol: "HTTP" # Use HTTP to connect to the argo-cd server
              tls: true

    - repoURL: {{ .Values.repository.url }}
      path: core/extras/argocd
      targetRevision: HEAD
