apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: cert-manager
  namespace: argocd

spec:
  project: core-services
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: {{ .Values.destination.server }}
    namespace: cert-manager

  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: 1.14.5
      chart: cert-manager
      helm:
        valuesObject:
          installCRDs: true

    - repoURL: {{ .Values.repository.url }}
      path: core/extras/cert-manager
      targetRevision: HEAD
      helm:
        values: |
          domain: {{ .Values.domain }}
