apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: external-dns
  namespace: argocd

spec:
  project: core-services
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: {{ .Values.destination.server }}
    namespace: external-dns

  sources:
    - repoURL: registry-1.docker.io/bitnamicharts # OCI registry
      chart: external-dns
      targetRevision: 7.5.2
      helm:
        values: |-
          provider: cloudflare
          cloudflare:
            secretName: cloudflare-api-token # Token should be stored under key of 'cloudflare_api_token'
            proxied: true # Default to proxying

    - repoURL: {{ .Values.repository.url }}
      path: core/extras/external-dns
      targetRevision: HEAD
