apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: gatekeeper
  namespace: argocd

spec:
  project: core-services
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: {{ .Values.destination.server }}
    namespace: gatekeeper-system

  sources:
    - repoURL: https://open-policy-agent.github.io/gatekeeper/charts
      targetRevision: 3.15.1
      # 3.16 have an annoying issue with mutatingwebhookconfiguration.webhooks.matchConditions being an empty list, but
      # the live manifest stripping away that empty list, causing out-of-sync (unless values are added)
      # For now, donwgrading is the least-effort choice -- might look into argocd's ignoreDifferences?
      chart: gatekeeper

    # - repoURL: {{ .Values.repository.url }}
    #   path: core/extras/gatekeeper
    #   targetRevision: HEAD
    #   helm:
    #     valuesObject:
    #       domain: {{ .Values.domain }}
