apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

spec:
  project: core-services
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: {{ .Values.destination.server }}
    namespace: kube-system # Required to be installed in kube-system

  sources:
    - repoURL: https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: 2.15.4
      helm:
        valuesObject:
          fullnameOverride: sealed-secrets-controller # kubeseal expects this name for the controller

    # - repoURL: {{ .Values.repository.url }}
    #   path: core/extras/sealed-secrets
    #   targetRevision: HEAD
